### ISSUE TITLE
Add messages to MessageAnnouncer

### ISSUE THREAD

**Issue by RalphORama** [podaboutlist/minecraft#18]
Add a list of helpful messages to MessageAnnouncer.

### Info

- [x] Description of the Homestead
- [x] How to click commands in these tips
- [x] VIP Rank with `/buy` and Patreon linking
- **Modifications to Vanilla Gameplay**
   - [x] Nether roof limit/kill zone
- [x] Bug reporting in `#minecraft-bugs-suggestions`
- [x] Celeste shooting stars
- [x] **BlockLocker:** one sign protects multiple chests/etc.
- [x] Emojis
   - [x] In chat
   - [x] On signs
   - [x] In commands
- [x] Hidden Lorax sapling replanting
- [x] Marriage mechanics
- **McMMO**
   - [x] Concept
   - [ ] Abilities
   - [x] Double drops
   - [x] Enchanted (mending) books from fishing
- [x] **MoreMeat:** extra drops
- **ShopKeepers**
   - [x] `/kit shopkeepers`
   - [x] World Trade Center info
   - [x] `/warp wtc`
   - [ ] Removing shopkeepers, getting back Shopkeeper spawn eggs
- **TimeControl**
   - [x] Ratio of sleepers (30%)
   - [x] Night speed
- **ViaBackwards / ViaVersion**
   - [x] Client versions supported
- **Villager Modifications**
   - [x] Item prices & limits (see `#minecraft-bugs-suggestions`
   - [x] Same prices as Solutio's shop at Spawn

### Commands

- [x] `/namecolor`
- [x] `/co i`
- [x] `/pvp`
- **EssentialsX**
   - [x] `/bed`
   - [x] `/hat`
   - [x] `/help`
   - [x] `/msg`
   - [x] `/r`
   - [x] `/mail`
   - [x] `/sethome` & `/home`
- **HyperDrive**
   - [x] `/warps`
- **BlockLocker**
   - [x] Adding a 2nd person
   - [x] Adding more than 3 people (2nd sign)
   - [x] `[Redstone]`
   - [x] `[Everyone]`
   - [x] `[Timer:X]`
- **GSit**
   - [x] `/sit`
   - [x] `/sit toggle`
- **McMMO**
   - [x] `/mcrank`
   - [x] `/mctop`
   - [x] `/mcability`
   - [x] `/mcscoreboard <keep/clear>`
   - [ ] Ability commands
- **ShowItem**
   - [x] `/show` (+default radius)
   - [x] `/show <player>`
   - [x] `%item%`, `%itemoffhand%`

### VIP Features

- **BlockLocker**
   - [x] VIP group access
- **EssentialsX**
   - [x] `/craftingtable`, `/loom`, etc.
   - Chat (+ `/msg`, signs)
      - [ ] magic code
      - [x] format codes
      - [x] RGB color codes
   - [x] RGB color codes in `/nick`
   - [x] `/condense`
   - [ ] `/editsign`
   - [x] increased `/sethome` limit (3 -> 6)
- **GSit**
   - [x] `/lay`
   - [x] `/bellyflop` (`/plank`)
   - [x] `/spin`
   - [x] `/crawl`
- **HyperDrive**
   - [x] Increased warp limit (3 -> 6)
- **MarriageMaster**
   - [x] Become a priest and perform marriages!
- **ShopKeepers**
   - [x] Increased shop limit (3 -> 6)
- **ShowItem**
   - [x] `/show -world`
   - [x] `/show -all`
   - [x] `/showinv`
   - [x] `/showender`
   - [x] `%inv%`, `%ender%`

### Backlog

- **CrazyCrates** (#7)
   - [ ] How to claim keys
   - [ ] How to see possible rewards
   - [ ] Where to find crate
   - [ ] Bonus keys for VIPs
- **Vouchers** (#7)
   -  How to use/where to get Vouchers

**Comment by RalphORama** [comment]
```yaml
command_rtp:
  - "[Tip] No hostile mobs spawn within the Homestead. If you'd like to fight some creeps, use /rtp!"
info_click_tip_commands:
  - "[Tip] You can click on the orange commands in these tips to try them yourself!"
command_buy:
  - "[Tip] Having fun? Want more? Consider using /buy to purchase VIP Status for $4.99/month!"
  - "[Tip] VIP Status unlocks even more features! (Full list available on the store page.)"
  - "[Tip] Patreon supporters automatically get VIP Status with their subscription!"
command_bed:
  - "[Tip] Teleport to the last bed you slept in with /bed!"
command_warps:
  - "[Tip] Browse the list of public warp locations with /warps!"
command_namecolor:
  - "[Tip] Customize the color of your username in chat with the /namecolor GUI!"
info_homestead:
  - "[Tip] The Homestead is a peaceful area around Spawn intended to house a city built by players on the server."
info_nether_roof_limit:
  - "[Tip] Watch out! There is a lethal void above the bedrock roof of the Nether. Don't go up there!"
info_bugs_suggestions:
  - "[Tip] Send your questions, comments, and concerns to the #mc-bugs-suggestions channel on Discord."
info_reports:
  - "[Tip] Report issues like griefing, use of slurs, etc. by opening a ticket in the #mc-reports Discord channel."
info_shooting_stars:
  - "[Tip] Shooting stars in the night sky sometimes crash to Earth, leaving a diamond and some XP where they fell..."
info_blocklocker_right_click:
  - "[Tip] Right-clicking on a chest, furnace, hopper, etc. with a sign will lock it!"
info_blocklocker_protection_area:
  - "[Tip] One sign is enough to lock multiple chests if the chests are next to each other."
info_blocklocker_protect_iron:
  - "[Tip] You can protect iron doors and trapdoors with signs just like chests."
info_emojichat:
  - "[Tip] Most default Discord :emoji: are available in chat! Try :tada: or :+1:!"

```
